image: docker:20.10.16

services:
  - docker:20.10.16

variables:
  DOCKER_HOST: tcp://docker:2375/  # Используем сокет для подключения к Docker
  DOCKER_DRIVER: overlay2

before_script:
  - docker info  # Проверяем доступность Docker
  - pip install --upgrade pip
  - pip install -r requirements.txt  # Установка зависимостей

stages:
  - test

unit_tests:
  stage: test
  script:
    - pytest ./backend/tests/test_main.py --junitxml=report.xml  # Запускаем тесты
  artifacts:
    paths:
      - report.xml  # Сохраняем отчет тестов

