image: python:3.8

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apt-get update && apt-get install -y docker.io  # Устанавливаем Docker
  - docker info  # Проверяем установку Docker
  - pip install --upgrade pip
  - pip install -r requirements.txt

stages:
  - test

unit_tests:
  stage: test
  script:
    - pytest ./backend/tests/test_main.py --junitxml=report.xml
  artifacts:
    paths:
      - report.xml
  rules:
    - when: always
