default:
  image: python:3.8

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r ./backend/requirements.txt

unit_tests:
  stage: test
  script:
    - pytest ./backend/tests/test_main.py --junitxml=report.xml
  artifacts:
    paths:
      - report.xml
  rules:
    - when: always
