image: docker:20.10.16  # Базовый образ Docker

services:
  - name: docker:dind  # Docker-in-Docker
    privileged: true  # Включение привилегированного режима для доступа к Docker-демону

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test

before_script:
  - docker info  # Проверяем, что Docker доступен
  - pip install --upgrade pip
  - pip install -r requirements.txt

unit_tests:
  stage: test
  script:
    - pytest ./backend/tests/test_main.py --junitxml=report.xml
  artifacts:
    paths:
      - report.xml
  rules:
    - when: always
