default:
  image: python:3.8

image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

unit_tests:
  stage: test
  script:
    - pytest ./backend/tests/test_main.py --junitxml=report.xml
  artifacts:
    paths:
      - report.xml
  rules:
    - when: always