FROM python:3.9-slim

WORKDIR /worker

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && apt-get clean

COPY requirements.txt /tmp/requirements.txt

# Set PYTHONPATH to /streamlit
ENV PYTHONPATH=/worker

RUN pip install --upgrade pip && pip install -r /tmp/requirements.txt



# Expose the Streamlit port
EXPOSE 8501

COPY . .
